BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBB BBBBBB

BBBBB BBBBB
XXXXXX XXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  XXXXXXX
   XXXXXXXXXXX X
       XXXXXX XXXXX
       XXXXXXXXXXXXXXXXX XXXXX
   X

   XXXXXX X
       XXXXXX XXX
       XXXXXXX XXXXX
       XXXXXXXXXXXXXXXXX XXXXXXXX
   X
  XXXXXXXX
XXXXXX
  XXXX XXXXXX XX XXX XXXXXX XXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXX

  XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX


  XXXXXXXX

   XXX X X XX
   XXXXXXXX XXXXXX X
       XX XX XX XX X
           X X XX
           XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXX XXXXX X XX
           XXX XXXXXXXXXXXX X XX
           XXX XX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXX
           XXXXXXXX XXXXXXX X
               XX XXXXXX XX XXXX X
                   XXXXXXXXXXXXXXXXXX
                   X X XX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

               X XXXX X
                   XXXXX X XXXXX X XX
                   XX XXXXXXXXXXXXX X XXXXXX X
                       XXXXXXXXXXXX X XXXXX X XXXXXXXXXXXXX X XX
                   X
                   XXXXXXXXXXXXXXXX X XXXXXXXXXXXX  X    XXXX
               X
           X
       X
   X

   XXXXXXX


  XXXXXXXXX



BBBBBBBB
